FROM python:3.12-slim

COPY requirements-streaming.txt /tmp/requirements-streaming.txt
RUN pip install --no-cache-dir -r /tmp/requirements-streaming.txt
WORKDIR /opt/project
ENV PYTHONPATH=/opt/project
CMD ["python", "-m", "streaming.python_consumer"]
